FROM node:12-alpine

RUN mkdir -p /home/node/api/node_modules && chown -R node:node /home

WORKDIR /home/node/api

COPY package*.json yarn.* ./

USER node

RUN yarn install

COPY --chown=node:node . . 

EXPOSE 8080

ENTRYPOINT [ "./init.sh" ]