version: "3"

services:

  node-app:
    container_name: ijournal-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - postgresDb

  postgresDb: 
    container_name: ijournalDb
    image: postgres:12
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - postgres-data:/data
    ports:
        - "5432:5432"

volumes:
  postgres-data: