version: "3"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ijournal-api
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    command: yarn dev:start
    depends_on:
      - databasej
  database: 
    container_name: ijournalDb
    image: postgres:12
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - postgres-data:/data
    ports:
        - "5432:5432"

volumes:
  postgres-data: